# Puerto
server.port=${SERVER_PORT}

# Configuración común de la base de datos
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Configuración del contexto de la aplicación
server.servlet.context-path=/api 

# Nombre de la aplicación
spring.application.name=backend-mrp

#Habilitar api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Definir la ruta de la documentación de la API
springdoc.swagger-ui.path=/docs

# Configuracion de la autenticacion JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Superadmin credentials
superadmin.email=${SU_EMAIL}
superadmin.password=${SU_PASSWORD}

